name: Run flask app

on:
  workflow_dispatch:
  schedule:
    - cron: "28 */5 * * *"
  
jobs:
  run_flask:
    runs-on: ubuntu-latest
    - name: Checkout Repository
      uses: actions/checkout@v3.5.3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
